[package]
name = "blog_os"
version = "0.1.0"
authors = ["monkslc <monkslc@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.9.8"
lazy_static = { version = "1.0", features = ["spin_no_std"] }
rlibc = "1.0.0"
spin = "0.5.2"
volatile = "0.2.6"
